server:
  port: ${PORT:8761}

spring:  
  application:
    name: discovery-server
    
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl: 
      defaultZone: http://localhost:8762/eureka/