node {

    withMaven(maven:'maven') {

        stage('Checkout') {
            git url: 'https://github.com/avinash10584/spring-microservices.git', 
            	credentialsId: 'github-avinash10584', branch: 'master'
        }

        stage('Build') {
        	dir ('spring-microservices-service-discovery') {
	            sh 'mvn clean install'
	
	            def pom = readMavenPom file:'pom.xml'
	            print pom.version
	            env.version = pom.version
            }
        }

		stage('Push Image') {
			dir ('spring-microservices-service-discovery') {
            docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
            	def app = docker.build "spring-boot-microservices:discovery-service-${env.version}"
                app.push("${BUILD_NUMBER}")
                app.push("latest")
            }
            }
        }        
        
    /*    stage ('Run') {
            docker.image("localhost:5000/discovery-service:${env.version}").run('-p 8761:8761 -h discovery --name discovery')
        }

        stage ('Final') {
            build job: 'account-service-pipeline', wait: false
        }    */  

    }

}